### ISSUE TITLE
techtinkering.com down

### ISSUE THREAD

**Issue by pamoroso** [LawrenceWoodman/techtinkering.com#1]
When visiting techtinkering.com I've been getting the error `DNS_PROBE_FINISHED_NXDOMAIN` for the past few days, and the tool Down for Everyone or Just Me confirms the site is down. Is techtinkering.com still maintained?

**Comment by lawrencewoodman** [comment]
I have just updated the DNS records and it is all working now.  Thanks for letting me know.

**Comment by pamoroso** [comment]
I confirm it's back online. Thanks to you for the great resource.
